export const ERROR_CODES = {
    MISSING_FIELDS: "MISSING_FIELDS",
    EMAIL_EXIST: "EMAIL_EXISTS",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    INVALID_CREDENTIAL: "INVALID_CREDENTIAL",
    INVALID_REQUEST: "INVALID_REQUEST",
    UNAUTHORIZED: "UNAUTHRIZED",
    GROUP_NOT_FOUND: "GROUP_NOT_FOUND",
    NOT_MEMBER: "NOT_MEMBER",
    ALREADY_JOINED: "ALREADY_JOINED",
    SENTENCE_NOT_FOUND: "SENTENCE_NOT_FOUND",
    NOT_SENTENCE_OWNER: "NOT_SENTENCE_OWNER"
} as const;