export const ERROR_CODES = {
    MISSING_FIELDS: "MISSING_FIELDS",
    EMAIL_EXIST: "EMAIL_EXISTS",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    INVALID_CREDENTIAL: "INVALID_CREDENTIAL",
    INVALID_REQUEST: "INVALID_REQUEST",
    UNAUTHORIZED: "UNAUTHRIZED"
} as const;